version: "3.8"

services:
  poetry-project:
    container_name: tix2go
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command:
      - /bin/bash
      - -c
      - poetry install
        && poetry run uvicorn src.main:app --reload --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: tix2go-db
    environment:
      MYSQL_ROOT_PASSWORD: tix2go
      MYSQL_DATABASE: tix2go
      MYSQL_USER: tix2go
      MYSQL_PASSWORD: tix2go
    ports:
      - "3306:3306"
    volumes:
      - tix2godb:/var/lib/mysql

volumes:
  tix2godb:
    external: false
