version: "3.8"

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - /bin/bash
      - -c
      - . .venv/bin/activate
        && uvicorn src.main:app --reload --host=0.0.0.0 --port=8000
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15.4
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  s3:
    image: minio/minio
    entrypoint: sh
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
    restart: always
    volumes:
      - minio_data:/data
    command: -c 'mkdir -p /data/dev && minio server --console-address :9001 /data'


volumes:
  mysql_data:
    external: false
  redis_data:
    external: false
  minio_data:
    external: false
  pg_data:
    external: false