"""poster_image

Revision ID: 078bf30c0831
Revises: 52e8f9099ebe
Create Date: 2023-10-11 16:38:21.982308

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "078bf30c0831"
down_revision: Union[str, None] = "52e8f9099ebe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "performances", sa.Column("poster_image_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f("performances_poster_image_id_fkey"),
        "performances",
        "images",
        ["poster_image_id"],
        ["id"],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        op.f("performances_poster_image_id_fkey"), "performances", type_="foreignkey"
    )

    op.drop_column("performances", "poster_image_id")

    # ### end Alembic commands ###
