"""distance_from_stage

Revision ID: c4a20d3e43ff
Revises: 40f9e73859b0
Create Date: 2023-10-31 18:06:34.927983

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4a20d3e43ff"
down_revision: Union[str, None] = "40f9e73859b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seats", sa.Column("distance_from_stage", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seats", "distance_from_stage")
    # ### end Alembic commands ###
