"""accessible_seat

Revision ID: 40f9e73859b0
Revises: 96c4d9e42e6e
Create Date: 2023-10-31 18:01:15.893617

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40f9e73859b0"
down_revision: Union[str, None] = "96c4d9e42e6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column("accessible_seats_info", sa.String(length=256), nullable=True),
    )
    op.add_column("seats", sa.Column("is_accessible", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seats", "is_accessible")
    op.drop_column("areas", "accessible_seats_info")
    # ### end Alembic commands ###
