"""hot

Revision ID: 4427fc458733
Revises: d02f7be034ff
Create Date: 2023-10-20 09:56:31.344135

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4427fc458733"
down_revision: Union[str, None] = "d02f7be034ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hot_performances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("performance_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["performance_id"],
            ["performances.id"],
            name=op.f("hot_performances_performance_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("hot_performances_pkey")),
    )
    op.create_index(
        op.f("hot_performances_id_idx"), "hot_performances", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("hot_performances_id_idx"), table_name="hot_performances")
    op.drop_table("hot_performances")
    # ### end Alembic commands ###
