"""casting_performance_id

Revision ID: 52e8f9099ebe
Revises: 833c3884c9d1
Create Date: 2023-10-11 13:48:04.194922

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52e8f9099ebe"
down_revision: Union[str, None] = "833c3884c9d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("castings", sa.Column("performance_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("castings_performance_id_fkey"),
        "castings",
        "performances",
        ["performance_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("castings_performance_id_fkey"), "castings", type_="foreignkey"
    )
    op.drop_column("castings", "performance_id")
    # ### end Alembic commands ###
