"""init

Revision ID: 6d3f958ea2a2
Revises: 
Create Date: 2023-09-27 06:41:04.945937

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d3f958ea2a2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("performance_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("areas_pkey")),
    )
    op.create_index(op.f("areas_id_idx"), "areas", ["id"], unique=False)
    op.create_table(
        "discounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("performance_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("discount_rate", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("discounts_pkey")),
    )
    op.create_index(op.f("discounts_id_idx"), "discounts", ["id"], unique=False)
    op.create_table(
        "performances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("running_time", sa.String(length=30), nullable=False),
        sa.Column("grade", sa.String(length=30), nullable=False),
        sa.Column("begin", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("pre_booking_enabled", sa.Boolean(), nullable=False),
        sa.Column("pre_booking_closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("performances_pkey")),
    )
    op.create_index(op.f("performances_id_idx"), "performances", ["id"], unique=False)
    op.create_table(
        "seat_grades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("performance_id", sa.Uuid(), nullable=False),
        sa.Column("discount_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("seat_grades_pkey")),
    )
    op.create_index(op.f("seat_grades_id_idx"), "seat_grades", ["id"], unique=False)
    op.create_table(
        "seats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=False),
        sa.Column("seat_grade_id", sa.Uuid(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("row", sa.Integer(), nullable=False),
        sa.Column("col", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("seats_pkey")),
    )
    op.create_index(op.f("seats_id_idx"), "seats", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_email_idx"), "users", ["email"], unique=True)
    op.create_index(op.f("users_id_idx"), "users", ["id"], unique=False)
    op.create_index(op.f("users_username_idx"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("users_username_idx"), table_name="users")
    op.drop_index(op.f("users_id_idx"), table_name="users")
    op.drop_index(op.f("users_email_idx"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("seats_id_idx"), table_name="seats")
    op.drop_table("seats")
    op.drop_index(op.f("seat_grades_id_idx"), table_name="seat_grades")
    op.drop_table("seat_grades")
    op.drop_index(op.f("performances_id_idx"), table_name="performances")
    op.drop_table("performances")
    op.drop_index(op.f("discounts_id_idx"), table_name="discounts")
    op.drop_table("discounts")
    op.drop_index(op.f("areas_id_idx"), table_name="areas")
    op.drop_table("areas")
    # ### end Alembic commands ###
