"""schedule_casting

Revision ID: 78278aa4133e
Revises: acfac32d3e3f
Create Date: 2023-10-04 08:39:54.571810

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78278aa4133e"
down_revision: Union[str, None] = "acfac32d3e3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("address_name", sa.String(length=150), nullable=False),
        sa.Column("place_name", sa.String(length=150), nullable=False),
        sa.Column("kakao_place_name", sa.String(length=150), nullable=False),
        sa.Column("kakao_place_url", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("locations_pkey")),
    )
    op.create_index(op.f("locations_id_idx"), "locations", ["id"], unique=False)
    op.create_table(
        "performers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("performers_pkey")),
    )
    op.create_index(op.f("performers_id_idx"), "performers", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
    )
    op.create_index(op.f("roles_id_idx"), "roles", ["id"], unique=False)
    op.create_table(
        "castings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("performer_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["performer_id"], ["performers.id"], name=op.f("castings_performer_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("castings_role_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("castings_pkey")),
    )
    op.create_index(op.f("castings_id_idx"), "castings", ["id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("performance_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["performance_id"],
            ["performances.id"],
            name=op.f("schedules_performance_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("schedules_pkey")),
    )
    op.create_index(op.f("schedules_id_idx"), "schedules", ["id"], unique=False)
    op.create_table(
        "schedule_casts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("casting_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["casting_id"], ["castings.id"], name=op.f("schedule_casts_casting_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("schedule_casts_schedule_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("schedule_casts_pkey")),
    )
    op.create_index(
        op.f("schedule_casts_id_idx"), "schedule_casts", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("schedule_casts_id_idx"), table_name="schedule_casts")
    op.drop_table("schedule_casts")
    op.drop_index(op.f("schedules_id_idx"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("castings_id_idx"), table_name="castings")
    op.drop_table("castings")
    op.drop_index(op.f("roles_id_idx"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("performers_id_idx"), table_name="performers")
    op.drop_table("performers")
    op.drop_index(op.f("locations_id_idx"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
