"""seat_grade

Revision ID: 808c48916d0b
Revises: 7cf4cfb98216
Create Date: 2023-10-09 11:01:05.039713

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "808c48916d0b"
down_revision: Union[str, None] = "7cf4cfb98216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seat_grades",
        sa.Column(
            "latest_cursor",
            sa.String(length=256),
            sa.Computed(
                "CONCAT(created_at, ':', id)",
            ),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("seat_grades_latest_cursor_idx"),
        "seat_grades",
        ["latest_cursor"],
        unique=False,
    )
    op.drop_column("seat_grades", "discount_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seat_grades", sa.Column("discount_id", mysql.CHAR(length=32), nullable=False)
    )
    op.drop_index(op.f("seat_grades_latest_cursor_idx"), table_name="seat_grades")
    op.drop_column("seat_grades", "latest_cursor")
    # ### end Alembic commands ###
