"""performer_description_nullable

Revision ID: 833c3884c9d1
Revises: 91a2020d549e
Create Date: 2023-10-11 13:05:08.214417

"""
from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "833c3884c9d1"
down_revision: Union[str, None] = "91a2020d549e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "performers", "description", existing_type=mysql.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "performers", "description", existing_type=mysql.TEXT(), nullable=False
    )
    # ### end Alembic commands ###
