"""role_performance_relation

Revision ID: 91a2020d549e
Revises: c1383873b06c
Create Date: 2023-10-11 12:42:56.306811

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91a2020d549e"
down_revision: Union[str, None] = "c1383873b06c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("performance_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("roles_performance_id_fkey"),
        "roles",
        "performances",
        ["performance_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("roles_performance_id_fkey"), "roles", type_="foreignkey")
    op.drop_column("roles", "performance_id")
    # ### end Alembic commands ###
