"""area_cursor

Revision ID: b671ee08b4ec
Revises: f2b0d6174bf4
Create Date: 2023-10-09 07:21:06.875626

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b671ee08b4ec"
down_revision: Union[str, None] = "f2b0d6174bf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column(
            "latest_cursor",
            sa.String(length=256),
            sa.Computed(
                "CONCAT(created_at, ':', id)",
            ),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("areas_latest_cursor_idx"), "areas", ["latest_cursor"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("areas_latest_cursor_idx"), table_name="areas")
    op.drop_column("areas", "latest_cursor")
    # ### end Alembic commands ###
