"""seat_name

Revision ID: c1383873b06c
Revises: 808c48916d0b
Create Date: 2023-10-09 11:07:38.005881

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1383873b06c"
down_revision: Union[str, None] = "808c48916d0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seats", sa.Column("name", sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seats", "name")
    # ### end Alembic commands ###
