"""genre

Revision ID: d02f7be034ff
Revises: e3bfcff60fe3
Create Date: 2023-10-15 13:53:27.324794

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d02f7be034ff"
down_revision: Union[str, None] = "e3bfcff60fe3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("genres", sa.Column("ident", sa.String(length=30), nullable=False))
    op.add_column(
        "performances", sa.Column("genre_idents", mysql.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("performances", "genre_idents")
    op.drop_column("genres", "ident")
    # ### end Alembic commands ###
