"""kakao_login

Revision ID: ee2b14285f1d
Revises: 6d3f958ea2a2
Create Date: 2023-09-28 03:22:19.677090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee2b14285f1d"
down_revision: Union[str, None] = "6d3f958ea2a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("kakao_id", sa.String(length=256), nullable=True))
    op.create_index(op.f("users_kakao_id_idx"), "users", ["kakao_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("users_kakao_id_idx"), table_name="users")
    op.drop_column("users", "kakao_id")
    # ### end Alembic commands ###
