"""avatar_image

Revision ID: f2b0d6174bf4
Revises: 78278aa4133e
Create Date: 2023-10-06 03:41:00.591299

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2b0d6174bf4"
down_revision: Union[str, None] = "78278aa4133e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("extension", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("images_pkey")),
    )
    op.create_index(op.f("images_id_idx"), "images", ["id"], unique=False)
    op.add_column(
        "performances",
        sa.Column(
            "latest_cursor",
            sa.String(length=256),
            sa.Computed(
                "CONCAT(created_at, ':', id)",
            ),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("performances_latest_cursor_idx"),
        "performances",
        ["latest_cursor"],
        unique=False,
    )
    op.add_column("users", sa.Column("avatar_image_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("users_avatar_image_id_fkey"),
        "users",
        "images",
        ["avatar_image_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_avatar_image_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "avatar_image_id")
    op.drop_index(op.f("performances_latest_cursor_idx"), table_name="performances")
    op.drop_column("performances", "latest_cursor")
    op.drop_index(op.f("images_id_idx"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
